import Student from "../models/studentmodel.js";

// 1. Create - Add Student
export const addStudent = async (req, res) => {
    try {
        const studentData = req.body;

        // MUHIIM: Haddii uu rollNumber ka yimid frontend-ka isagoo "Autogenerated" ah,
        // waa inaan tirtirnaa si hook-ga model-ka uu mid cusub u soo saaro.
        if (studentData.rollNumber === "" || studentData.rollNumber === "Autogenerated") {
            delete studentData.rollNumber;
        }

        const newStudent = new Student(studentData);
        await newStudent.save();
        
        res.json({ success: true, message: "Ardayga waa la diiwaan-geliyay", data: newStudent });
    } catch (error) {
        console.error("Backend Error:", error);
        // Haddii uu yahay duplicate error
        if (error.code === 11000) {
            return res.json({ success: false, message: "Roll Number-ka waa mid hore u jiray!" });
        }
        res.json({ success: false, message: error.message });
    }
};

// 2. Update - Edit Student
export const updateStudent = async (req, res) => {
    try {
        const { id } = req.params;
        const updateData = req.body;

        // Waxaan isticmaaleynaa findById si aan u kicinno 'save' hook haddii loo baahdo
        // Laakiin caadiyan findByIdAndUpdate ayaa ka dhakhsiyo badan.
        const updatedStudent = await Student.findByIdAndUpdate(id, updateData, { new: true });
        
        if (!updatedStudent) {
            return res.json({ success: false, message: "Ardayga lama helin" });
        }

        res.json({ success: true, message: "Xogta ardayga waa la beddelay", data: updatedStudent });
    } catch (error) {
        res.json({ success: false, message: error.message });
    }
};

// 3. Read - Get All Students (With Subjects detail)
export const getStudents = async (req, res) => {
    try {
        const students = await Student.find({}).populate("subjects");
        res.json({ success: true, data: students });
    } catch (error) {
        res.json({ success: false, message: error.message });
    }
};

// 4. Delete - Remove Student
export const deleteStudent = async (req, res) => {
    try {
        const { id } = req.params;
        await Student.findByIdAndDelete(id);
        res.json({ success: true, message: "Ardayga waa la tirtiray" });
    } catch (error) {
        res.json({ success: false, message: error.message });
    }
};

// 5. Pay Fee - Lacag ka qabasho bishan ah
export const payFee = async (req, res) => {
    try {
        const { studentId, amount, evcReference } = req.body;
        const currentMonth = new Date().toISOString().slice(0, 7); // Soo saaraya "2026-02"

        const student = await Student.findById(studentId);
        if (!student) return res.json({ success: false, message: "Ardayga lama helin" });

        // Cusboonaysii xogta lacagta
        student.lastPaymentMonth = currentMonth;
        student.paymentHistory.push({
            amount,
            month: currentMonth,
            evcReference
        });

        await student.save();
        res.json({ success: true, message: "Lacagta bishan waa la diiwaangeliyay" });
    } catch (error) {
        res.json({ success: false, message: error.message });
    }
};

